### ISSUE TITLE
Blowing up MagicMirror-out.log (+8GB in 48 hours)

### ISSUE THREAD

**Issue by manuelsinger-msft** [robotfishe/MMM-Tronity#1]
MMM-Tronity is filling up MagicMirror-out.log with 
[LOG] Socket notification received GET_CAR_DATA
[LOG] vehicle ID.....
[LOG] Vehicle data url https://api.tronity.tech....
[LOG] Sending GET request with auth token: .....................................................................
Creating more than 8 GB(!) data within 48 hours.

**Comment by robotfishe** [comment]
Caused by setting update interval to 5 milliseconds - see #3

**Comment by manuelsinger-msft** [comment]
Can we have an option to NOT log all this data in MagicMirror-out.log (or a shortened version of the token)?
